const express = require('express')
const app = express()
const port = 3001;
Canvas = require('canvas');
var fs = require("fs");

var arrayToImage = require("array-to-image")
 
const dataimg = new Uint8ClampedArray(256 * 256 * 4);
 
for(let i = 0; i < dataimg.length; i += 4) {
    dataimg[i] = 255; // r
    dataimg[i + 1] = 0; // g
    dataimg[i + 2] = 0; // b
    dataimg[i + 3] = 255; // a
}
//const img = arrayToImage.getImgFromArr(dataimg);

app.get('/getimg', function (req, res) {
    fs.readFile(__dirname + '/7.jpg', function(err, data) {
        if (err) throw err;
        var img = new Canvas.Image; // Create a new Image
        img.src = data;

        // Initialiaze a new Canvas with the same dimensions
        // as the image, and get a 2D drawing context for it.
        var canvas = new Canvas.Canvas(img.width, img.height);
        var ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0, img.width / 4, img.height / 4);

        res.write('<html><body>');
        res.write('<img src="' + canvas.toDataURL() + '" />');
        res.write('</body></html>');
        res.end();
    });

})

app.get('/listUsers', function (req, res) {
    fs.readFile(__dirname + "/" + "users.json", 'utf8', function (err, data) {
       console.log( data );
       res.end( data );
    });
 })
 var user = {
    "user4" : {
       "name" : "Pussy Lover",
       "password" : "password4",
       "profession" : "teacher",
       "id": 4
    }
 }
 app.post('/addUser', function (req, res) {
    // First read existing users.
    fs.readFile( __dirname + "/" + "users.json", 'utf8', function (err, data) {
       data = JSON.parse( data );
       data["user4"] = user["user4"];
       console.log( data );
       res.end( JSON.stringify(data));
    });
 })
 app.post('/saveimg', function (req, res) {
    var img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0"
    + "NAAAAKElEQVQ4jWNgYGD4Twzu6FhFFGYYNXDUwGFpIAk2E4dHDRw1cDgaCAASFOffhEIO"
    + "3gAAAABJRU5ErkJggg==";
// strip off the data: url prefix to get just the base64-encoded bytes
var data = img.replace(/^data:image\/\w+;base64,/, "");
var buf = new Buffer.from(data, 'base64');
fs.writeFile(__dirname + "/" + "image.png", buf, err => {
    if (err) throw err;
    console.log('Saved!');
})

    });
    // string generated by canvas.toDataURL()
  
  app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
  })